ynput/ayon-blender

client/ayon_blender/api/ops.py

Another Blender addon or script may, before AYON's initialization scripts run have already done other things like initializing a `QApplication` instance. We should allow that and not error on such a conflict with another addon.
It's now not inheriting from QApplication anymore because we weren't using the instance itself really anywhere else - it was all classmethod access anyway. 
This may fix [the issue reported by Luciano Munoz on Ynput Discord](https://discord.com/channels/517362899170230292/1260337785403867218/1261001453581897758)

Allow existing QtWidgets.QApplication instance to exist

---

client/ayon_blender/api/ops.py

This PR #7 introduced changes to how the QApplication is generated and accessed - however it seems I missed one that was only called on non-windows platforms, which of course I didn't test on.
This PR should fix the bug reported [here](https://community.ynput.io/t/setting-up-blender-4-2-linux-mint-error-with-the-ayon-operators/1574/11) and with that should also fix the current `ayon-blender` state for Mac/Linux.
Original error:
```python
Traceback (most recent call last):
File "/home/hannah/.local/share/AYON/addons/blender_0.2.1-dev.1/ayon_blender/api/ops.py", line 198, in _process_app_events
if app._instance:
^^^^^^^^^^^^^
AttributeError: 'PySide6.QtWidgets.QApplication' object has no attribute '_instance'
```
1. Run Blender on non-windows platform
2. Make sure the AYON Qt tools work as …

Fix QApplication access on platforms other than Windows

---

client/ayon_blender/plugins/publish/collect_workfile.py

This is an extension of another PR in ayon-core: https://github.com/ynput/ayon-core/pull/786
Together they generate a better validation report for when the publish started from an unsaved workfile.

Do not error on unsaved workfile

---

client/ayon_blender/api/ops.py
client/ayon_blender/api/pipeline.py

This PR is to add unit scale options into AYON menu
Make sure to turn on `ayon+settings://blender/unit_scale_settings/enabled` 
We need to consider whether `ayon+settings://blender/unit_scale_settings/apply_on_opening` is required for some enhancement, as the window of log message does not show on top.
2. AYON -> Set Unit Scale

add set unit scale options into AYON menu

---

client/ayon_blender/plugins/publish/validate_deadline_publish.py

Resolve https://github.com/ynput/ayon-blender/issues/16
I also refactored the validator a little bit so that it won't always error out.
2. Create Render Instance
3. Publish
4. If validate render output for deadline errors out, make sure you perform repair action
5. Publish
6. It should be rendered successfully.

Add a check on scene render filepath and repair action in Validate Render Output for Deadline

---

client/ayon_blender/plugins/load/load_cache.py

Resolve #2 
These changes consolidate the way imported hierarchy is re-parented in Blender upon cache load. 
Only top nodes of "Empty" objects without any transforms will be skipped.
Published hierarchy:
Loaded hierarchy (note how only Empty.002 is removed cause unecessary):
This is my first MR for the project, please do let me know if any troubles.
1. Create scene with meshes 
2. Parent some of the meshes to new empty objects
3. Apply random transform on both empty and mesh objects
4. Publish the empty as a pointcacheMain
5. Load the pointcache
6. Ensure all of the transforms are preserved

Fix transforms on Empty object children not maintained by ABC cache load.

---

client/ayon_blender/api/ops.py
client/ayon_blender/plugins/load/load_cache.py
client/ayon_blender/plugins/load/load_camera_abc.py

This PR is to make sure the libpath is still updated in the cache modifier without removing the modifier.
We need to discuss if the cache modifiers should be implemented in the load function as there is still issue updating the libpath when the users uses set version to the loaded assets for the first time.
2. Load Pointcache/model/camera with alembic loader
3. Set version with scene inventory

Alembic loaders update the libpath without the removal of the cache modifier

---

client/ayon_blender/plugins/publish/extract_usd.py

Fix optional support for Extract USD Model
It was optional by default, and had options in settings but the optional toggle was not shown nor used.
1. Optional toggle should show in publisher UI for model product type.
2. The inactive (disabled in publisher UI) state should be adhered to and do no export when toggled off.

Fix optional support for Extract USD Model

---

client/ayon_blender/api/pipeline.py
client/ayon_blender/plugins/load/load_image_compositor.py

Add a loader action to load media to the blender compositor in a managed way.
Fixes #32 
1. Load some renders into the compositor

Add load to compositor loader

---

client/ayon_blender/api/colorspace.py
client/ayon_blender/api/lib.py
client/ayon_blender/plugins/create/create_animation.py
client/ayon_blender/plugins/create/create_camera.py
client/ayon_blender/plugins/create/create_pointcache.py
client/ayon_blender/plugins/create/create_render.py
client/ayon_blender/plugins/create/create_review.py
client/ayon_blender/plugins/publish/collect_instance_frame_range.py
client/ayon_blender/plugins/publish/collect_render.py
client/ayon_blender/plugins/publish/collect_review.py
client/ayon_blender/plugins/publish/extract_abc.py
client/ayon_blender/plugins/publish/extract_abc_animation.py
client/ayon_blender/plugins/publish/extract_camera_abc.py
client/ayon_blender/plugins/publish/validate_frame_range.py

- Discard 'step' for pointcache/animation since it did not influence the output alembic at all.
- Default the frame range to current context task entity instead of current scene
- Add handle start and handle end attributes to be explicit about that, defaulting to current task attribs.
- Actually fix passing along the start and end frame to the Alembic export from creator to instance data.
- Add support for validating frame range against the instance's task/folder entity for review, pointcache, animation, etc. + support repair method for those.
- Remove redundant 'scene overrides' that tried to use that to affect what the alembic export did - but it didn't do much, and the export command has dedicated arguments for that.
I have no idea whether the `step` attribute does work for the other …

Fix frame range attributes for instances + validations

---

client/ayon_blender/api/plugin.py
client/ayon_blender/plugins/load/load_image_compositor.py

Adds support for "Switch Asset" in scene inventory for blender loaders.
Based on comment [here](https://github.com/ynput/ayon-blender/pull/38#discussion_r1763243308)
1. Validate the 'switch' works as intended for managed Blender loaders

Add switch asset support for all loaders inheriting from `BlenderLoader`

---

client/ayon_blender/api/lib.py
client/ayon_blender/plugins/load/load_cache.py

This PR is the quick fix on the object path not being filled into the mesh sequence modifier.
n/a
2. Load PointCache, Model and Animation
3. Update/Setting Version to the geometry
4. Repeat 3
5. Object path of the modifier should be filled.

Make sure there is object path filled into the cache modifier

---

client/ayon_blender/api/pipeline.py

Correctly parse compositor node containers using both new and old container id key
Reported on Discord [here](https://discord.com/channels/517362899170230292/563751989075378201/1297855852866437152)
1. Load image to compositor
2. Check scene inventory (AYON > Manage...) it should list the loaded container.

Fix managing of loaded compositor image nodes

---

client/ayon_blender/api/render_lib.py

Render path: Do not enforce backslashes to support UNC path.
Quick hotfix for #69
@jrsndl could you test this?
1. Set up rendering using UNC path
2. Render path should resolve correctly at rendertime.

Render path: Do not enforce backslashes to support UNC path.

---

client/ayon_blender/plugins/load/load_image_compositor.py
client/ayon_blender/plugins/load/load_image_shader.py

Fix setting of `colorspace`
Fixes #72
1. Load image to compositor and load image to shader should correctly set colorspace.

Load Image to comp or shader: fix applying colorspace 

---

client/ayon_blender/api/pipeline.py
client/ayon_blender/plugins/load/load_action.py
client/ayon_blender/plugins/load/load_audio.py
client/ayon_blender/plugins/load/load_blend.py
client/ayon_blender/plugins/load/load_blendscene.py
client/ayon_blender/plugins/load/load_cache.py
client/ayon_blender/plugins/load/load_camera_abc.py
client/ayon_blender/plugins/load/load_camera_fbx.py
client/ayon_blender/plugins/load/load_fbx.py
client/ayon_blender/plugins/load/load_image_compositor.py
client/ayon_blender/plugins/load/load_layout_json.py
client/ayon_blender/plugins/load/load_look.py

This PR is to add project_name as part of the container data regarding to the implementation of https://github.com/ynput/ayon-core/pull/1005 
Test along with the installed addon with https://github.com/ynput/ayon-core/pull/1005
2. Load Assets from any product type(s)

Add project_name as part of the container data

---

client/ayon_blender/api/ops.py

This PR is to add version 
Resolve https://github.com/ynput/ayon-blender/issues/75
Should we introduce the validator or integrator to check/save workfile with version?
1. Following the testing step in 75 to enable version up workfile
2. Launch Blender and `version up current workfile` would show up in the menu

Version up current workfile in ayon menu

---

client/ayon_blender/api/render_lib.py
client/ayon_blender/plugins/create/create_render.py
client/ayon_blender/plugins/load/load_animation.py
client/ayon_blender/plugins/publish/collect_render.py
client/ayon_blender/plugins/publish/validate_deadline_publish.py

This PR is to make sure the AOVs from render layer nodes always connected to the Output File Node.
Resolve https://github.com/ynput/ayon-blender/issues/37
n/a
1. Add some render settings in Ayon server
2. Create Render Instance with your camera
3. Publish

The AOVs from render layer nodes always connected to the Output File Node

---

client/ayon_blender/api/render_lib.py
client/ayon_blender/plugins/publish/collect_render.py
client/ayon_blender/plugins/publish/validate_deadline_publish.py

This PR is to make sure the deadline setting correctly propagated to publisher UI and fix the small bug on collecting aov files when the multilayer is on.
Resolve https://github.com/ynput/ayon-blender/issues/88
n/a
2. Create Render Instance with mutlilayer options on in ayon setting
3. Publish
4. The deadline parameter should be propagated correctly accordingly to the Publisher UI.

Make sure the deadline setting correctly propagated to publisher UI

---

client/ayon_blender/api/lib.py
client/ayon_blender/api/render_lib.py

Resolve https://github.com/ynput/ayon-blender/issues/51
Add the compatible check on the renderer when it is set to EEVEE in regards to the recent changes on the renderer name in bpy.
n/a
1. Create Render Instance with EEVEE being as default renderer in ayon setting
2. Should be working.

backward compatibility for blender eevee renderer newer than 4.2.2

---

client/ayon_blender/api/ops.py

Fix support for Blender 4.4+
See: https://developer.blender.org/docs/release_notes/4.4/python_api/
> Python-defined classes based on Blender types (like `Operator`, `PropertyGroup`, etc.) that define their own `__new__`/`__init__` constructors must now call the parent's matching function, and pass on generic positional and keyword arguments.
Fix https://github.com/ynput/ayon-blender/issues/101#issuecomment-2679138882
1. Download Blender 4.4 beta
2. Launch with AYON integration

Fix operator for Blender 4.4+

---

client/ayon_blender/api/capture.py

Blender currently is not clearing the localview when closing a window. (Known bug: https://projects.blender.org/blender/blender/issues/104069) That caused the extract review to fail due to max 16 local views are allowed.
I have added a function to restore to the global view before removing the window.
1. Create Review publish instance\
2. Publish Review 15+ times (versions up to v016)

Return to global view before closing a window

---

client/ayon_blender/blender_addon/startup/init.py

Raise a more descriptive error when a user has launched AYON Blender without the `--python-use-system-env` argument
It would now error something like:
```
Traceback (most recent call last):
File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'ayon_core'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "<stdin>", line 5, in <module>
ModuleNotFoundError: No module named 'ayon_core'. This usually happens if Blender is launched without the --python-use-system-env argument. Make sure you have the Blender application 'Arguments' configured correctly so that Blender has access to the launched context's PYTHONPATH.
```
1. Remove the `--python-use-system-env` argument from application settings
2. Launch Blender
3. The …

Raise descriptive error when Blender launched without -python-use-system-env argument

---

client/ayon_blender/plugins/publish/extract_fbx_animation.py

This PR is to fix the Attribute Error shown with `bake_action_objects`  due to the changes of the argument `bakeOptions`
Related to https://github.com/ynput/ayon-blender/pull/104
1. Launch Blender 4.0 and 3.X.X 
2. Create Animation and publish
3. Both should be published successfully

Extract Fbx Animation: `bake_action_objects` support Blender 4.1+

---

client/ayon_blender/api/lib.py
client/ayon_blender/plugins/publish/extract_blend.py

This PR is to make sure publishing blenderScene product will strip namespace and container data
Resolve https://github.com/ynput/ayon-blender/issues/113
Make sure testing the scenarios below:
1. Publish with loaded asset
2. Publish without loaded asset
3. Publish with or without loaded asset
1. Launch Blender 
4. Create BlenderScene product with/without the loaded assets
5. Publish
6. Create New Scene in Blender
7. Load the published asset

Publishing BlenderScene product should strip namespace and container data 

---

client/ayon_blender/plugins/publish/collect_file_dependencies.py

Fix `CollectFileDependencies` with recent `ayon-deadline` releases since deadline addon https://github.com/ynput/ayon-deadline/pull/49 or if `ayon-deadline is not available (e.g. addon not in bundle)
Should avoid error:
```python
*** WRN: >>> { filter_pyblish_plugins }: [  FAILED to apply settings on plugin CollectFileDependencies  ]
=======================
'BlenderSubmitDeadline'
=======================
Traceback (most recent call last):
File "F:\dev\ayon-core\client\ayon_core\pipeline\publish\lib.py", line 452, in filter_pyblish_plugins
plugin.apply_settings(project_settings)
File "F:\dev\ayon-blender\client\ayon_blender\plugins\publish\collect_file_dependencies.py", line 19, in apply_settings
settings = project_settings[ "deadline"]["publish"]["BlenderSubmitDeadline" ]  # noqa …
```

Fix `CollectFileDependencies` with recent `ayon-deadline` releases

---

client/ayon_blender/plugins/create/create_blendScene.py

Create Blend Scene: Remove `maintain_selection` attribute. It does nothing.
This attribute only existed due to inheriting it from the legacy creators before switching to the new publisher (where it used to go through code like [this](https://github.com/ynput/ayon-core/blob/c2f3d8b114ecd93871029144bc81a77ad841758e/client/ayon_core/pipeline/create/legacy_create.py#L208)). However, I am pretty sure now it's unused.
Equivalent to:
- https://github.com/ynput/ayon-nuke/pull/127
- https://github.com/ynput/ayon-houdini/pull/282
1. Create Blend Scene should not be affected.

Create Blend Scene: Remove `maintain_selection` attribute

---

client/ayon_blender/plugins/publish/validate_no_animation.py
server/settings/publish_plugins.py

This PR is to implement the optional validator to check if the objects have animation data for model, rig and blendScene product, similar to what we have to check no animation data for model product in maya.
Resolve https://github.com/ynput/ayon-blender/issues/132
Tested with the objects with or without animation data.
1. Create BlendScene, Rig, Model instance by selections
2. Publish

Implementation of Validate No Animation

---

client/ayon_blender/api/lib.py

This PR is to add support for striping namespace for shader nodes with texture images when extracting blend scene
Fixes https://github.com/ynput/ayon-blender/issues/116
n/a
1. Create Rig/BlendScene with shader nodes(texture-image based) 
2. Publish

Supports stripping namespace for shader nodes for texture image

---

client/ayon_blender/plugins/load/load_blend_link.py

Explicit the pubish types that needs to be loaded via `load_blend_link` this way this option does not appear for any custom client-specific product with `.blend` representation which maybe confusing and incompatible.
1. Ensure this loader still appears for AYON vanilla product
2. Ensure this loader does not appear for any custom product type with `.blend` representation.

Explicit publish types for load_blend_link.

---

client/ayon_blender/addon.py
client/ayon_blender/api/lib.py

Fixes:
* Blender 4.4+, when using `AYON_BLENDER_USE_SYSTEM_PATH`, returned value was always `False`.
* When using `BLENDER_USER_SCRIPTS`, default user preferences were not loaded if `BLENDER_USER_SCRIPTS` was not explictely overrided.
Blender 4.4+
1. Ensure that when `AYON_BLENDER_USE_SYSTEM_PATH` is either set to `0` or `1`, this get properly detected in the starting code.
Blender<4.4
1. Ensure default user preferences are loaded enven if `BLENDER_USER_SCRIPTS` is not defined

Fix load user addons from paths when starting Blender.

---

client/ayon_blender/api/lib.py
client/ayon_blender/api/plugin.py
client/ayon_blender/plugins/load/load_animation.py
client/ayon_blender/plugins/load/load_blend.py
client/ayon_blender/plugins/load/load_blendscene.py
client/ayon_blender/plugins/load/load_image_shader.py

As mentioned in https://github.com/ynput/ayon-blender/issues/118, the maximum data-block names length will be increased from 63 to 255 bytes. This PR is to add backward compatibility for some of the function for character truncation in our blender plugins.
n/a
1. Load animation/blend/blendScene
2. Should be working
3. Publish BlendScene
4. Should be also working.

Implement backward compatibility for character truncation in 5.0

---

client/ayon_blender/plugins/load/load_blend.py
client/ayon_blender/plugins/load/load_blend_link.py
client/ayon_blender/plugins/load/load_blendscene.py

This PR is to ensure the loaded assets would be linked back to the collection of which users manually linked the loaded asset during up-versioning and setting version.
Fixes https://github.com/ynput/ayon-blender/issues/142
n/a
1. Load Model or any proudct type related to load blend
2. Add new collection and parent your loaded asset under the collection
3. Updating and Removing instances should be all good.

Load Blend: loaded assets should be linked back to the user-defined collection during update

---

client/ayon_blender/plugins/create/create_render.py

Use kwargs to call product name functions and use cached data to call them if possible.
This is preparation for future change in `get_product_name` functionality and update of already added change in `get_product_name` method.
1. Product names are calculated correctly.

Create: Use kwargs to call product name functions
